### ISSUE TITLE
Convert project web site to Jekyll

### ISSUE THREAD

**Issue by hollasch** [TEALSK12/teals-minecraft#8]
The project web site is currently written in standard HTML + CSS. Converting this over to Jekyll would make it more accessible to contributors, and would take advantage of the many templates and tools that GitHub supports through Jekyll.

See [About GitHub Pages and Jekyll](https://help.github.com/articles/about-github-pages-and-jekyll/) for more information.

**Comment by hawkerm** [comment]
Feel free to check out my config file I use for Space Battle here: https://github.com/Mikeware/SpaceBattleArena/blob/master/_config.yml

I set it up, so I can use the gh-pages repository to host on GitHub and have it read from the doc folder of my main project's markup.

**Comment by hollasch** [comment]
@hawkerm It doesn't look like you're using Jekyll any more. Am I correct in thinking it's just HTML now?

**Comment by hawkerm** [comment]
@hollasch curious, what makes you say that? Jekyll compiles down to HTML in the end, so to the browser it's just a collection of HTML pages.  But in the back-end of my doc repro it's all markdown.

I need to resetup my tool chain on my new machine now though...

**Comment by hollasch** [comment]
Interesting, looks like you have a non-standard setup, where your doc sources are in `master` in the `docs/` directory, and your `gh-pages` branch contains the generated HTML output. The standard GitHub Jekyll setup is to put Jekyll configuration and source `*.md` files in the `gh-pages` branch (or now, the `docs` directory), and GitHub auto-generates the resulting HTML site on the fly, served to the project web site.

That said, getting Jekyll and its requirements to run in a PC environment was painful enough that I wrapped up my experiment after a day of fiddling, as it would require a fussy setup for every other author who wanted to view results locally as they develop new materials.

**Comment by hollasch** [comment]
I'm going to table this for now.

**Comment by hawkerm** [comment]
@hollasch good to know about the GitHub auto-generate.  I was setting it up in my master so I could move docs alongside the code as I made changes, generate locally to ensure docs looked good, and then push to the docs branch the changes that snapped to the code when I made a new release.
